name: clean_flutter_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  intl: ^0.17.0
  flutter_modular: ^5.0.3
  build_runner: ^2.3.3
  modular_test: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build
  watch: flutter pub run build_runner watch --delete-conflicting-outputs

flutter_intl:
  enabled: true
